import assets from "./assets";

const InstitutionsData = [
  {
    id: 1,
    fullName: "University of California, Berkeley",
    location: "Berkeley, CA",
    type: "Public",
    numberFireSectors: 3,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
    createdAt: "2022-09-22",
    image: assets.building,
    sectors: [
      {
        id: "FS-11",
        name: "Sector 1 ",
        area: 100,
        description: "Sector 1 de la institución 1",
        observations: "Sector 1 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [
          {
            id: "M-11",
            name: "Cristal",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-12",
            name: "Madera",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-13",
            name: "Metal",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
        ],
      },
      {
        id: "FS-12",
        name: "Sector 2",
        area: 100,
        description: "Sector 2 de la institución 1",
        observations: "Sector 2 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [
          {
            id: "M-21",
            name: "Cristal",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
        ],
      },
      {
        id: "FS-13",
        name: "Sector 3",
        area: 100,
        description: "Sector 3 de la institución 1",
        observations: "Sector 3 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [
          {
            id: "M-31",
            name: "Cristal",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-32",
            name: "Madera",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
        ],
      },
    ],
  },
  {
    id: 2,
    fullName: "Stanford University",
    location: "Stanford, CA",
    type: "Private",
    numberFireSectors: 2,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
    createdAt: "2022-09-22",
    image: assets.building,
    sectors: [
      {
        id: "FS-14",
        name: "Sector 4",
        area: 100,
        description: "Sector 4 de la institución 2",
        observations: "Sector 4 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [
          {
            id: "M-41",
            name: "Cristal",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-42",
            name: "Madera",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
        ],
      },
      {
        id: "FS-15",
        name: "Sector 5",
        area: 100,
        description: "Sector 5 de la institución 2",
        observations: "Sector 5 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [],
      },
    ],
  },
  {
    id: 3,
    fullName: "Harvard University",
    location: "Cambridge, MA",
    type: "Private",
    numberFireSectors: 4,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
    createdAt: "2022-09-22",
    image: assets.building,
    sectors: [
      {
        id: "FS-16",
        name: "Sector 6",
        area: 100,
        description: "Sector 6 de la institución 3",
        observations: "Sector 6 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [
          {
            id: "M-61",
            name: "Cristal",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
        ],
      },
      {
        id: "FS-17",
        name: "Sector 7",
        area: 100,
        description: "Sector 7 de la institución 3",
        observations: "Sector 7 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [
          {
            id: "M-71",
            name: "Cristal",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-72",
            name: "Madera",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-73",
            name: "Metal",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-74",
            name: "Aceite",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-75",
            name: "Papel",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-76",
            name: "Plástico",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-77",
            name: "Textil",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-78",
            name: "Vidrio",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
          {
            id: "M-79",
            name: "Otros",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
        ],
      },
      {
        id: "FS-18",
        name: "Sector 8",
        area: 100,
        description: "Sector 8 de la institución 3",
        observations: "Sector 8 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [],
      },
      {
        id: "FS-19",
        name: "Sector 9",
        area: 100,
        description: "Sector 9 de la institución 3",
        observations: "Sector 9 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [],
      },
    ],
  },
  {
    id: 4,
    fullName: "Yale University",
    location: "New Haven, CT",
    type: "Private",
    numberFireSectors: 6,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
    createdAt: "2022-09-22",
    image: assets.building,
    sectors: [
      {
        id: "FS-20",
        name: "Sector 10",
        area: 100,
        description: "Sector 10 de la institución 4",
        observations: "Sector 10 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [
          {
            id: "M-80",
            name: "Madera",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
        ],
      },
      {
        id: "FS-21",
        name: "Sector 11",
        area: 100,
        description: "Sector 11 de la institución 4",
        observations: "Sector 11 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [],
      },
      {
        id: "FS-22",
        name: "Sector 12",
        area: 100,
        description: "Sector 12 de la institución 4",
        observations: "Sector 12 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [
          {
            id: "M-81",
            name: "Madera",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
        ],
      },
      {
        id: "FS-23",
        name: "Sector 13",
        area: 100,
        description: "Sector 13 de la institución 4",
        observations: "Sector 13 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [
          {
            id: "M-82",
            name: "Madera",
            name: "Madera",
            heatValue: 100,
            heatValue2: 10.0,
            Sector_Material: {
              createdAt: "2022-09-22",
              updatedAt: "2022-09-22",
              weight: 80.5,
              totalCalorificValue: 55.5,
            },
          },
        ],
      },
      {
        id: "FS-24",
        name: "Sector 14",
        area: 100,
        description: "Sector 14 de la institución 4",
        observations: "Sector 14 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [],
      },
      {
        id: "FS-25",
        name: "Sector 15",
        area: 100,
        description: "Sector 15 de la institución 4",
        observations: "Sector 15 observaciones",
        createdAt: "2022-09-22",
        updatedAt: "2022-09-22",
        totalFireload: 0,
        date: "December 12, 2019 at 12:10 PM",
        image: assets.place,
        materials: [],
      },
    ],
  },
  {
    id: 5,
    fullName: "Princeton University",
    location: "Princeton, NJ",
    type: "Private",
    numberFireSectors: 0,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
    createdAt: "2022-09-22",
    image: assets.building,
    sectors: [],
  },
  {
    id: 6,
    fullName: "Columbia University",
    location: "New York, NY",
    type: "Private",
    numberFireSectors: 0,
    description:
      "The action painter abstract expressionists were directly influenced by automatism. Pollock channelled this into producing gestural. Lorem ipsum dolor sit amet consectetur adipiscing elit consequat accumsan sapien, lectus convallis malesuada odio curae habitasse dignissim nascetur. Nulla sed velit erat vitae leo sem inceptos diam fames arcu hendrerit, quis ultrices in eleifend posuere ipsum conubia porttitor felis. Ullamcorper platea penatibus ornare egestas nulla ligula hendrerit nisl suscipit sociosqu maximus, tincidunt aptent habitant purus pharetra ultrices dapibus laoreet nisi lacinia. Porta malesuada netus vel sapien conubia porttitor aliquam ut pretium ante litora molestie senectus magna egestas sociosqu, eget aliquet fames pharetra felis posuere varius fringilla quisque in arcu montes eu ullamcorper.",
    createdAt: "2022-09-22",
    image: assets.building,
    sectors: [],
  },
];

export { InstitutionsData };
